import numpy as np


def displacePattern(W, delta, M):
    """
    Function generates the BF settings associated with the displaced pattern.
    The initial BF vector W gets displaced by delta equivalent directions
    (-1...1) that was generated by an array having M elements

    Parameters:
        W: BF vector (numpy array)
        delta: displacement value
        M: number of array elements

    Returns:
        W_dd: displaced BF vector
    """
    # Phase-shifting vector
    D_delta = np.diag(np.exp(1j * np.pi * np.arange(1, M + 1) * delta))

    # BF settings associated with the displaced pattern
    # Non-conjugated, as BF vector is conjugated by convention
    W_dd = D_delta @ W

    return W_dd
